---

- name: restart php-fpm
  service:
    name: php{{ php_version }}-fpm
    state: restarted
    enabled: yes

- name: restart nginx
  service:
    name: nginx
    state: restarted
    enabled: yes

- name: reload nginx
  service:
    name: nginx
    state: reloaded
    enabled: yes

- name: reload apache
  service:
    name: apache2
    state: reloaded

- name: restart apache
  service:
    name: apache2
    state: restarted
