---

# Ansible
ansible_ssh_user: "root"

# General
project_name: "docs"
project_password: "5<bmGaj%FZBG#q"
remote_user: "{{ docs }}"
remote_group: "{{ docs }}"
home_dir: "/root"

# Domain
domain: "docs.cod3labs.com"
protocol: "https"
port: "443"

# Project
repository: "git@github.com:cod3labsteam/docs.git"

# Nginx

# Let's Encrypt
letsencrypt_email: "thecod3labs@gmail.com"

# Let's Encrypt certificate settings
certbot_create_if_missing: true
certbot_create_method: "standalone"
certbot_admin_email: "{{ letsencrypt_email }}"
certbot_auto_renew: true
certbot_auto_renew_user: "{{ ansible_user | default(lookup('env', 'USER')) }}"
certbot_auto_renew_hour: "3"
certbot_auto_renew_minute: "30"
certbot_auto_renew_options: "--quiet --no-self-upgrade"
certbot_certs:
  - domains:
      - "{{ domain }}"
certbot_create_standalone_stop_services:
  - nginx
