---
- name: Update repository and upgrade packages
  apt:
    upgrade: dist
    update_cache: yes
  tags: [ system ]

- name: Install aptitude
  apt:
    name: aptitude
    update_cache: yes
    state: latest
    force_apt_get: yes
  tags: [ system ]

