---

- import_playbook: bootstrap.yml

- name: Apply common configuration to all nodes
  hosts: all
  remote_user: root
  roles:
    - common

- name: Install and configure application requirements
  hosts: web
  remote_user: root
  vars_files:
    - vars/main.yml
  roles:
    - geerlingguy.apache
    - geerlingguy.php-versions
    - geerlingguy.php
    - geerlingguy.php-mysql
    - geerlingguy.php-memcached
    - geerlingguy.certbot
    - geerlingguy.firewall
    - geerlingguy.composer
